import { TarotCard } from "./tarotCard.interface";

export const cardsDeck: TarotCard[] = [
    { id: 1,  src: "Tarot-deck-images/Tarot_00_Fool.jpg",               alt: "The Fool",        name: "The Fool" },
    { id: 2,  src: "Tarot-deck-images/Tarot_01_Magician.jpg",           alt: "The Magician",    name: "The Magician" },
    { id: 3,  src: "Tarot-deck-images/Tarot_02_High_Priestess.jpg",     alt: "The High Priestess", name: "The High Priestess" },
    { id: 4,  src: "Tarot-deck-images/Tarot_03_Empress.jpg",            alt: "The Empress",     name: "The Empress" },
    { id: 5,  src: "Tarot-deck-images/Tarot_04_Emperor.jpg",            alt: "The Emperor",     name: "The Emperor" },
    { id: 6,  src: "Tarot-deck-images/Tarot_05_Hierophant.jpg",         alt: "The Hierophant",  name: "The Hierophant" },
    { id: 7,  src: "Tarot-deck-images/Tarot_06_Lovers.jpg",             alt: "The Lovers",      name: "The Lovers" },
    { id: 8,  src: "Tarot-deck-images/Tarot_07_Chariot.jpg",            alt: "The Chariot",     name: "The Chariot" },
    { id: 9,  src: "Tarot-deck-images/Tarot_08_Strength.jpg",           alt: "Strength",        name: "Strength" },
    { id: 10, src: "Tarot-deck-images/Tarot_09_Hermit.jpg",             alt: "The Hermit",      name: "The Hermit" },
    { id: 11, src: "Tarot-deck-images/Tarot_10_Wheel_of_Fortune.jpg",   alt: "Wheel of Fortune", name: "Wheel of Fortune" },
    { id: 12, src: "Tarot-deck-images/Tarot_11_Justice.jpg",            alt: "Justice",         name: "Justice" },
    { id: 13, src: "Tarot-deck-images/Tarot_12_Hanged_Man.jpg",         alt: "The Hanged Man",  name: "The Hanged Man" },
    { id: 14, src: "Tarot-deck-images/Tarot_13_Death.jpg",              alt: "Death",           name: "Death" },
    { id: 15, src: "Tarot-deck-images/Tarot_14_Temperance.jpg",         alt: "Temperance",      name: "Temperance" },
    { id: 16, src: "Tarot-deck-images/Tarot_15_Devil.jpg",              alt: "The Devil",       name: "The Devil" },
    { id: 17, src: "Tarot-deck-images/Tarot_16_Tower.jpg",              alt: "The Tower",       name: "The Tower" },
    { id: 18, src: "Tarot-deck-images/Tarot_17_Star.jpg",               alt: "The Star",        name: "The Star" },
    { id: 19, src: "Tarot-deck-images/Tarot_18_Moon.jpg",               alt: "The Moon",        name: "The Moon" },
    { id: 20, src: "Tarot-deck-images/Tarot_19_Sun.jpg",                alt: "The Sun",         name: "The Sun" },
    { id: 21, src: "Tarot-deck-images/Tarot_20_Judgement.jpg",          alt: "Judgement",       name: "Judgement" },
    { id: 22, src: "Tarot-deck-images/Tarot_21_World.jpg",              alt: "The World",       name: "The World" },

    // Cups
    { id: 23, src: "Tarot-deck-images/Cups01.jpg",          alt: "Ace of Cups",     name: "Ace of Cups" },
    { id: 24, src: "Tarot-deck-images/Cups02.jpg",          alt: "Two of Cups",     name: "Two of Cups" },
    { id: 25, src: "Tarot-deck-images/Cups03.jpg",          alt: "Three of Cups",   name: "Three of Cups" },
    { id: 26, src: "Tarot-deck-images/Cups04.jpg",          alt: "Four of Cups",    name: "Four of Cups" },
    { id: 27, src: "Tarot-deck-images/Cups05.jpg",          alt: "Five of Cups",    name: "Five of Cups" },
    { id: 28, src: "Tarot-deck-images/Cups06.jpg",          alt: "Six of Cups",     name: "Six of Cups" },
    { id: 29, src: "Tarot-deck-images/Cups07.jpg",          alt: "Seven of Cups",   name: "Seven of Cups" },
    { id: 30, src: "Tarot-deck-images/Cups08.jpg",          alt: "Eight of Cups",   name: "Eight of Cups" },
    { id: 31, src: "Tarot-deck-images/Cups09.jpg",          alt: "Nine of Cups",    name: "Nine of Cups" },
    { id: 32, src: "Tarot-deck-images/Cups10.jpg",          alt: "Ten of Cups",     name: "Ten of Cups" },
    { id: 33, src: "Tarot-deck-images/page-of-cups.jpg",    alt: "Page of Cups",    name: "Page of Cups" },
    { id: 34, src: "Tarot-deck-images/Knight-of-cups.jpg",  alt: "Knight of Cups",  name: "Knight of Cups" },
    { id: 35, src: "Tarot-deck-images/Queen-of-cups.jpg",   alt: "Queen of Cups",   name: "Queen of Cups" },
    { id: 36, src: "Tarot-deck-images/King-of-cups.jpg",    alt: "King of Cups",    name: "King of Cups" },

    // Swords
    { id: 37, src: "Tarot-deck-images/Swords01.jpg",        alt: "Ace of Swords",   name: "Ace of Swords" },
    { id: 38, src: "Tarot-deck-images/Swords02.jpg",        alt: "Two of Swords",   name: "Two of Swords" },
    { id: 39, src: "Tarot-deck-images/Swords03.jpg",        alt: "Three of Swords", name: "Three of Swords" },
    { id: 40, src: "Tarot-deck-images/Swords04.jpg",        alt: "Four of Swords",  name: "Four of Swords" },
    { id: 41, src: "Tarot-deck-images/Swords05.jpg",        alt: "Five of Swords",  name: "Five of Swords" },
    { id: 42, src: "Tarot-deck-images/Swords06.jpg",        alt: "Six of Swords",   name: "Six of Swords" },
    { id: 43, src: "Tarot-deck-images/Swords07.jpg",        alt: "Seven of Swords", name: "Seven of Swords" },
    { id: 44, src: "Tarot-deck-images/Swords08.jpg",        alt: "Eight of Swords", name: "Eight of Swords" },
    { id: 45, src: "Tarot-deck-images/Swords09.jpg",        alt: "Nine of Swords",  name: "Nine of Swords" },
    { id: 46, src: "Tarot-deck-images/Swords10.jpg",        alt: "Ten of Swords",   name: "Ten of Swords" },
    { id: 47, src: "Tarot-deck-images/page-of-swords.jpg",  alt: "Page of Swords",  name: "Page of Swords" },
    { id: 48, src: "Tarot-deck-images/Knight-of-swords.jpg",alt: "Knight of Swords",name: "Knight of Swords" },
    { id: 49, src: "Tarot-deck-images/Queen-of-swords.jpg", alt: "Queen of Swords", name: "Queen of Swords" },
    { id: 50, src: "Tarot-deck-images/King-of-swords.jpg",  alt: "King of Swords",  name: "King of Swords" },

    // Wands
    { id: 51, src: "Tarot-deck-images/Wands01.jpg",         alt: "Ace of Wands",    name: "Ace of Wands" },
    { id: 52, src: "Tarot-deck-images/Wands02.jpg",         alt: "Two of Wands",    name: "Two of Wands" },
    { id: 53, src: "Tarot-deck-images/Wands03.jpg",         alt: "Three of Wands",  name: "Three of Wands" },
    { id: 54, src: "Tarot-deck-images/Wands04.jpg",         alt: "Four of Wands",   name: "Four of Wands" },
    { id: 55, src: "Tarot-deck-images/Wands05.jpg",         alt: "Five of Wands",   name: "Five of Wands" },
    { id: 56, src: "Tarot-deck-images/Wands06.jpg",         alt: "Six of Wands",    name: "Six of Wands" },
    { id: 57, src: "Tarot-deck-images/Wands07.jpg",         alt: "Seven of Wands",  name: "Seven of Wands" },
    { id: 58, src: "Tarot-deck-images/Wands08.jpg",         alt: "Eight of Wands",  name: "Eight of Wands" },
    { id: 59, src: "Tarot-deck-images/Wands09.jpg",         alt: "Nine of Wands",   name: "Nine of Wands" },
    { id: 60, src: "Tarot-deck-images/Wands10.jpg",         alt: "Ten of Wands",    name: "Ten of Wands" },
    { id: 61, src: "Tarot-deck-images/page-of-wands.jpg",   alt: "Page of Wands",   name: "Page of Wands" },
    { id: 62, src: "Tarot-deck-images/Knight-of-wands.jpg", alt: "Knight of Wands", name: "Knight of Wands" },
    { id: 63, src: "Tarot-deck-images/Queen-of-wands.jpg",  alt: "Queen of Wands",  name: "Queen of Wands" },
    { id: 64, src: "Tarot-deck-images/King-of-wands.jpg",   alt: "King of Wands",   name: "King of Wands" },

    // Pentacles
    { id: 65, src: "Tarot-deck-images/Pents01.jpg",         alt: "Ace of Pentacles", name: "Ace of Pentacles" },
    { id: 66, src: "Tarot-deck-images/Pents02.jpg",         alt: "Two of Pentacles", name: "Two of Pentacles" },
    { id: 67, src: "Tarot-deck-images/Pents03.jpg",         alt: "Three of Pentacles", name: "Three of Pentacles" },
    { id: 68, src: "Tarot-deck-images/Pents04.jpg",         alt: "Four of Pentacles", name: "Four of Pentacles" },
    { id: 69, src: "Tarot-deck-images/Pents05.jpg",         alt: "Five of Pentacles", name: "Five of Pentacles" },
    { id: 70, src: "Tarot-deck-images/Pents06.jpg",         alt: "Six of Pentacles", name: "Six of Pentacles" },
    { id: 71, src: "Tarot-deck-images/Pents07.jpg",         alt: "Seven of Pentacles", name: "Seven of Pentacles" },
    { id: 72, src: "Tarot-deck-images/Pents08.jpg",         alt: "Eight of Pentacles", name: "Eight of Pentacles" },
    { id: 73, src: "Tarot-deck-images/Pents09.jpg",         alt: "Nine of Pentacles", name: "Nine of Pentacles" },
    { id: 74, src: "Tarot-deck-images/Pents10.jpg",         alt: "Ten of Pentacles", name: "Ten of Pentacles" },
    { id: 75, src: "Tarot-deck-images/page-of-pentacles.jpg", alt: "Page of Pentacles", name: "Page of Pentacles" },
    { id: 76, src: "Tarot-deck-images/Knight-of-pentacles.jpg", alt: "Knight of Pentacles", name: "Knight of Pentacles" },
    { id: 77, src: "Tarot-deck-images/Queen-of-pentacles.jpg", alt: "Queen of Pentacles", name: "Queen of Pentacles" },
    { id: 78, src: "Tarot-deck-images/King-of-pentacles.jpg", alt: "King of Pentacles", name: "King of Pentacles" },
];