import { TarotCard } from "./tarotCard.interface"

export const cardsDeck: TarotCard[] = [
    { id: 1,  image: '<img src="private-images/Tarot_00_Fool.jpg" class="small-card" alt="The Fool">',               name: 'The Fool' },
    { id: 2,  image: '<img src="private-images/Tarot_01_Magician.jpg" class="small-card" alt="The Magician">',       name: 'The Magician' },
    { id: 3,  image: '<img src="private-images/Tarot_02_High_Priestess.jpg" class="small-card" alt="The High Priestess">', name: 'The High Priestess' },
    { id: 4,  image: '<img src="private-images/Tarot_03_Empress.jpg" class="small-card" alt="The Empress">',         name: 'The Empress' },
    { id: 5,  image: '<img src="private-images/Tarot_04_Emperor.jpg" class="small-card" alt="The Emperor">',         name: 'The Emperor' },
    { id: 6,  image: '<img src="private-images/Tarot_05_Hierophant.jpg" class="small-card" alt="The Hierophant">',   name: 'The Hierophant' },
    { id: 7,  image: '<img src="private-images/Tarot_06_Lovers.jpg" class="small-card" alt="The Lovers">',           name: 'The Lovers' },
    { id: 8,  image: '<img src="private-images/Tarot_07_Chariot.jpg" class="small-card" alt="The Chariot">',         name: 'The Chariot' },
    { id: 9,  image: '<img src="private-images/Tarot_08_Strength.jpg" class="small-card" alt="Strength">',           name: 'Strength' },
    { id: 10, image: '<img src="private-images/Tarot_09_Hermit.jpg" class="small-card" alt="The Hermit">',           name: 'The Hermit' },
    { id: 11, image: '<img src="private-images/Tarot_10_Wheel_of_Fortune.jpg" class="small-card" alt="Wheel of Fortune">', name: 'Wheel of Fortune' },
    { id: 12, image: '<img src="private-images/Tarot_11_Justice.jpg" class="small-card" alt="Justice">',             name: 'Justice' },
    { id: 13, image: '<img src="private-images/Tarot_12_Hanged_Man.jpg" class="small-card" alt="The Hanged Man">',   name: 'The Hanged Man' },
    { id: 14, image: '<img src="private-images/Tarot_13_Death.jpg" class="small-card" alt="Death">',                 name: 'Death' },
    { id: 15, image: '<img src="private-images/Tarot_14_Temperance.jpg" class="small-card" alt="Temperance">',       name: 'Temperance' },
    { id: 16, image: '<img src="private-images/Tarot_15_Devil.jpg" class="small-card" alt="The Devil">',             name: 'The Devil' },
    { id: 17, image: '<img src="private-images/Tarot_16_Tower.jpg" class="small-card" alt="The Tower">',             name: 'The Tower' },
    { id: 18, image: '<img src="private-images/Tarot_17_Star.jpg" class="small-card" alt="The Star">',               name: 'The Star' },
    { id: 19, image: '<img src="private-images/Tarot_18_Moon.jpg" class="small-card" alt="The Moon">',               name: 'The Moon' },
    { id: 20, image: '<img src="private-images/Tarot_19_Sun.jpg" class="small-card" alt="The Sun">',                 name: 'The Sun' },
    { id: 21, image: '<img src="private-images/Tarot_20_Judgement.jpg" class="small-card" alt="Judgement">',         name: 'Judgement' },
    { id: 22, image: '<img src="private-images/Tarot_21_World.jpg" class="small-card" alt="The World">',            name: 'The World' },

    // Cups
    { id: 23, image: '<img src="private-images/Cups01.jpg" class="small-card" alt="Ace of Cups">',          name: 'Ace of Cups' },
    { id: 24, image: '<img src="private-images/Cups02.jpg" class="small-card" alt="Two of Cups">',          name: 'Two of Cups' },
    { id: 25, image: '<img src="private-images/Cups03.jpg" class="small-card" alt="Three of Cups">',        name: 'Three of Cups' },
    { id: 26, image: '<img src="private-images/Cups04.jpg" class="small-card" alt="Four of Cups">',         name: 'Four of Cups' },
    { id: 27, image: '<img src="private-images/Cups05.jpg" class="small-card" alt="Five of Cups">',         name: 'Five of Cups' },
    { id: 28, image: '<img src="private-images/Cups06.jpg" class="small-card" alt="Six of Cups">',          name: 'Six of Cups' },
    { id: 29, image: '<img src="private-images/Cups07.jpg" class="small-card" alt="Seven of Cups">',        name: 'Seven of Cups' },
    { id: 30, image: '<img src="private-images/Cups08.jpg" class="small-card" alt="Eight of Cups">',        name: 'Eight of Cups' },
    { id: 31, image: '<img src="private-images/Cups09.jpg" class="small-card" alt="Nine of Cups">',         name: 'Nine of Cups' },
    { id: 32, image: '<img src="private-images/Cups10.jpg" class="small-card" alt="Ten of Cups">',          name: 'Ten of Cups' },
    { id: 33, image: '<img src="private-images/page-of-cups.jpg" class="small-card" alt="Page of Cups">',  name: 'Page of Cups' },
    { id: 34, image: '<img src="private-images/Knight-of-cups.jpg" class="small-card" alt="Knight of Cups">', name: 'Knight of Cups' },
    { id: 35, image: '<img src="private-images/Queen-of-cups.jpg" class="small-card" alt="Queen of Cups">', name: 'Queen of Cups' },
    { id: 36, image: '<img src="private-images/King-of-cups.jpg" class="small-card" alt="King of Cups">',   name: 'King of Cups' },

    // Swords (fixed capitalization in names for consistency)
    { id: 37, image: '<img src="private-images/Swords01.jpg" class="small-card" alt="Ace of Swords">',     name: 'Ace of Swords' },
    { id: 38, image: '<img src="private-images/Swords02.jpg" class="small-card" alt="Two of Swords">',     name: 'Two of Swords' },
    { id: 39, image: '<img src="private-images/Swords03.jpg" class="small-card" alt="Three of Swords">',   name: 'Three of Swords' },
    { id: 40, image: '<img src="private-images/Swords04.jpg" class="small-card" alt="Four of Swords">',    name: 'Four of Swords' },
    { id: 41, image: '<img src="private-images/Swords05.jpg" class="small-card" alt="Five of Swords">',    name: 'Five of Swords' },
    { id: 42, image: '<img src="private-images/Swords06.jpg" class="small-card" alt="Six of Swords">',     name: 'Six of Swords' },
    { id: 43, image: '<img src="private-images/Swords07.jpg" class="small-card" alt="Seven of Swords">',   name: 'Seven of Swords' },
    { id: 44, image: '<img src="private-images/Swords08.jpg" class="small-card" alt="Eight of Swords">',   name: 'Eight of Swords' },
    { id: 45, image: '<img src="private-images/Swords09.jpg" class="small-card" alt="Nine of Swords">',    name: 'Nine of Swords' },
    { id: 46, image: '<img src="private-images/Swords10.jpg" class="small-card" alt="Ten of Swords">',     name: 'Ten of Swords' },
    { id: 47, image: '<img src="private-images/page-of-swords.jpg" class="small-card" alt="Page of Swords">', name: 'Page of Swords' },
    { id: 48, image: '<img src="private-images/Knight-of-swords.jpg" class="small-card" alt="Knight of Swords">', name: 'Knight of Swords' },
    { id: 49, image: '<img src="private-images/Queen-of-swords.jpg" class="small-card" alt="Queen of Swords">', name: 'Queen of Swords' },
    { id: 50, image: '<img src="private-images/King-of-swords.jpg" class="small-card" alt="King of Swords">', name: 'King of Swords' },

    // Wands
    { id: 51, image: '<img src="private-images/Wands01.jpg" class="small-card" alt="Ace of Wands">',       name: 'Ace of Wands' },
    { id: 52, image: '<img src="private-images/Wands02.jpg" class="small-card" alt="Two of Wands">',       name: 'Two of Wands' },
    { id: 53, image: '<img src="private-images/Wands03.jpg" class="small-card" alt="Three of Wands">',     name: 'Three of Wands' },
    { id: 54, image: '<img src="private-images/Wands04.jpg" class="small-card" alt="Four of Wands">',      name: 'Four of Wands' },
    { id: 55, image: '<img src="private-images/Wands05.jpg" class="small-card" alt="Five of Wands">',      name: 'Five of Wands' },
    { id: 56, image: '<img src="private-images/Wands06.jpg" class="small-card" alt="Six of Wands">',       name: 'Six of Wands' },
    { id: 57, image: '<img src="private-images/Wands07.jpg" class="small-card" alt="Seven of Wands">',     name: 'Seven of Wands' },
    { id: 58, image: '<img src="private-images/Wands08.jpg" class="small-card" alt="Eight of Wands">',     name: 'Eight of Wands' },
    { id: 59, image: '<img src="private-images/Wands09.jpg" class="small-card" alt="Nine of Wands">',      name: 'Nine of Wands' },
    { id: 60, image: '<img src="private-images/Wands10.jpg" class="small-card" alt="Ten of Wands">',       name: 'Ten of Wands' },
    { id: 61, image: '<img src="private-images/page-of-wands.jpg" class="small-card" alt="Page of Wands">', name: 'Page of Wands' },
    { id: 62, image: '<img src="private-images/Knight-of-wands.jpg" class="small-card" alt="Knight of Wands">', name: 'Knight of Wands' },
    { id: 63, image: '<img src="private-images/Queen-of-wands.jpg" class="small-card" alt="Queen of Wands">', name: 'Queen of Wands' },
    { id: 64, image: '<img src="private-images/King-of-wands.jpg" class="small-card" alt="King of Wands">', name: 'King of Wands' },

    // Pentacles
    { id: 65, image: '<img src="private-images/Pents01.jpg" class="small-card" alt="Ace of Pentacles">',   name: 'Ace of Pentacles' },
    { id: 66, image: '<img src="private-images/Pents02.jpg" class="small-card" alt="Two of Pentacles">',   name: 'Two of Pentacles' },
    { id: 67, image: '<img src="private-images/Pents03.jpg" class="small-card" alt="Three of Pentacles">', name: 'Three of Pentacles' },
    { id: 68, image: '<img src="private-images/Pents04.jpg" class="small-card" alt="Four of Pentacles">',  name: 'Four of Pentacles' },
    { id: 69, image: '<img src="private-images/Pents05.jpg" class="small-card" alt="Five of Pentacles">',  name: 'Five of Pentacles' },
    { id: 70, image: '<img src="private-images/Pents06.jpg" class="small-card" alt="Six of Pentacles">',   name: 'Six of Pentacles' },
    { id: 71, image: '<img src="private-images/Pents07.jpg" class="small-card" alt="Seven of Pentacles">', name: 'Seven of Pentacles' },
    { id: 72, image: '<img src="private-images/Pents08.jpg" class="small-card" alt="Eight of Pentacles">', name: 'Eight of Pentacles' },
    { id: 73, image: '<img src="private-images/Pents09.jpg" class="small-card" alt="Nine of Pentacles">',  name: 'Nine of Pentacles' },
    { id: 74, image: '<img src="private-images/Pents10.jpg" class="small-card" alt="Ten of Pentacles">',   name: 'Ten of Pentacles' },
    { id: 75, image: '<img src="private-images/page-of-pentacles.jpg" class="small-card" alt="Page of Pentacles">', name: 'Page of Pentacles' },
    { id: 76, image: '<img src="private-images/Knight-of-pentacles.jpg" class="small-card" alt="Knight of Pentacles">', name: 'Knight of Pentacles' },
    { id: 77, image: '<img src="private-images/Queen-of-pentacles.jpg" class="small-card" alt="Queen of Pentacles">', name: 'Queen of Pentacles' },
    { id: 78, image: '<img src="private-images/King-of-pentacles.jpg" class="small-card" alt="King of Pentacles">', name: 'King of Pentacles' },
];